//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Recruitment_Portal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/RecruitmentCard")]
        public string E_Recruitment_Portal_RecruitmentCard_RecruitmentCard_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_RecruitmentCard_RecruitmentCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/ApplicantCard")]
        public string E_Recruitment_Portal_ApplicantCard_ApplicantCard_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ApplicantCard_ApplicantCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/RiskCard")]
        public string E_Recruitment_Portal_RiskCard_RiskCard_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_RiskCard_RiskCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/CountriesRegions" +
            "")]
        public string E_Recruitment_Portal_CountriesRegions_CountriesRegions_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_CountriesRegions_CountriesRegions_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/Recruitment")]
        public string E_Recruitment_Portal_Recruitment_Recruitment_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_Recruitment_Recruitment_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/ApplicantJobEduc" +
            "ation")]
        public string E_Recruitment_Portal_ApplicantJobEducation_ApplicantJobEducation_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ApplicantJobEducation_ApplicantJobEducation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/FieldsofStudy")]
        public string E_Recruitment_Portal_FieldsofStudy_FieldsofStudy_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_FieldsofStudy_FieldsofStudy_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/Qualifications")]
        public string E_Recruitment_Portal_Qualifications_Qualifications_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_Qualifications_Qualifications_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/ProfMembership")]
        public string E_Recruitment_Portal_ProfMembership_ProfMembership_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ProfMembership_ProfMembership_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/ApplicantJobProf" +
            "essionalCourse")]
        public string E_Recruitment_Portal_ApplicantJobProfessionalCourse_ApplicantJobProfessionalCourse_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ApplicantJobProfessionalCourse_ApplicantJobProfessionalCours" +
                    "e_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/CompanyJobIndust" +
            "ries")]
        public string E_Recruitment_Portal_CompanyJobIndustries_CompanyJobIndustries_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_CompanyJobIndustries_CompanyJobIndustries_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/AcademicQualific" +
            "ations")]
        public string E_Recruitment_Portal_AcademicQualifications_AcademicQualifications_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_AcademicQualifications_AcademicQualifications_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/ApplicantHobbies" +
            "")]
        public string E_Recruitment_Portal_ApplicantHobbies_ApplicantHobbies_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ApplicantHobbies_ApplicantHobbies_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/Referees")]
        public string E_Recruitment_Portal_Referees_Referees_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_Referees_Referees_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/ApplicantJobprof" +
            "essionalmembership")]
        public string E_Recruitment_Portal_ApplicantJobprofessionalmembership_ApplicantJobprofessionalmembership_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ApplicantJobprofessionalmembership_ApplicantJobprofessionalm" +
                    "embership_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/ApplicantJobExpe" +
            "rience")]
        public string E_Recruitment_Portal_ApplicantJobExperience_ApplicantJobExperience_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ApplicantJobExperience_ApplicantJobExperience_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Page/Jobsapplied")]
        public string E_Recruitment_Portal_Jobsapplied_Jobsapplied_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_Jobsapplied_Jobsapplied_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileoffice.agilebiz.co.ke:12347/KMRC/WS/KMRC%20TEST/Codeunit/OnlinePortal" +
            "")]
        public string E_Recruitment_Portal_OnlinePortal_OnlinePortal {
            get {
                return ((string)(this["E_Recruitment_Portal_OnlinePortal_OnlinePortal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kmrcapp.kmrc.co.ke:7047/KMRC/WS/KMRC%20TEST/Page/ProfMemberships")]
        public string E_Recruitment_Portal_ProfMemberships_ProfMemberships_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_ProfMemberships_ProfMemberships_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kmrcapp.kmrc.co.ke:7047/KMRC/WS/KMRC%20TEST/Page/CompanyJobCard")]
        public string E_Recruitment_Portal_CompanyJobCard_CompanyJobCard_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_CompanyJobCard_CompanyJobCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.88.8:23802/KDB_LIVE/WS/KDBTEST/Page/CountyList")]
        public string E_Recruitment_Portal_CountyList_CountyList_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_CountyList_CountyList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.88.8:23802/KDB_LIVE/WS/KDBTEST/Page/Applicantjobapplied")]
        public string E_Recruitment_Portal_Applicantjobapplied_Applicantjobapplied_Service {
            get {
                return ((string)(this["E_Recruitment_Portal_Applicantjobapplied_Applicantjobapplied_Service"]));
            }
        }
    }
}
