//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace E_Recruitment_Portal.CompanyJobCard {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CompanyJobCard_Binding", Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class CompanyJobCard_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_KeyJobResponsibilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_AcademicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_ExperienceOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_KnowledgeRequiredOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_ProfessionalCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_ProfessionalMembershipOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_Position_SupervisingOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_AttachmentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CompanyJobCard_Service() {
            this.Url = global::E_Recruitment_Portal.Properties.Settings.Default.E_Recruitment_Portal_CompanyJobCard_CompanyJobCard_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event Delete_KeyJobResponsibilitiesCompletedEventHandler Delete_KeyJobResponsibilitiesCompleted;
        
        /// <remarks/>
        public event Delete_AcademicsCompletedEventHandler Delete_AcademicsCompleted;
        
        /// <remarks/>
        public event Delete_ExperienceCompletedEventHandler Delete_ExperienceCompleted;
        
        /// <remarks/>
        public event Delete_KnowledgeRequiredCompletedEventHandler Delete_KnowledgeRequiredCompleted;
        
        /// <remarks/>
        public event Delete_ProfessionalCourseCompletedEventHandler Delete_ProfessionalCourseCompleted;
        
        /// <remarks/>
        public event Delete_ProfessionalMembershipCompletedEventHandler Delete_ProfessionalMembershipCompleted;
        
        /// <remarks/>
        public event Delete_Position_SupervisingCompletedEventHandler Delete_Position_SupervisingCompleted;
        
        /// <remarks/>
        public event Delete_AttachmentsCompletedEventHandler Delete_AttachmentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CompanyJobCard")]
        public CompanyJobCard Read(string Job_ID) {
            object[] results = this.Invoke("Read", new object[] {
                        Job_ID});
            return ((CompanyJobCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Job_ID) {
            this.ReadAsync(Job_ID, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Job_ID, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Job_ID}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CompanyJobCard")]
        public CompanyJobCard ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((CompanyJobCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CompanyJobCard[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] CompanyJobCard_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((CompanyJobCard[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CompanyJobCard_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CompanyJobCard_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref CompanyJobCard CompanyJobCard) {
            object[] results = this.Invoke("Create", new object[] {
                        CompanyJobCard});
            CompanyJobCard = ((CompanyJobCard)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(CompanyJobCard CompanyJobCard) {
            this.CreateAsync(CompanyJobCard, null);
        }
        
        /// <remarks/>
        public void CreateAsync(CompanyJobCard CompanyJobCard, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        CompanyJobCard}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CompanyJobCard[] CompanyJobCard_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        CompanyJobCard_List});
            CompanyJobCard_List = ((CompanyJobCard[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CompanyJobCard[] CompanyJobCard_List) {
            this.CreateMultipleAsync(CompanyJobCard_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CompanyJobCard[] CompanyJobCard_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        CompanyJobCard_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref CompanyJobCard CompanyJobCard) {
            object[] results = this.Invoke("Update", new object[] {
                        CompanyJobCard});
            CompanyJobCard = ((CompanyJobCard)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(CompanyJobCard CompanyJobCard) {
            this.UpdateAsync(CompanyJobCard, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(CompanyJobCard CompanyJobCard, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        CompanyJobCard}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CompanyJobCard[] CompanyJobCard_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        CompanyJobCard_List});
            CompanyJobCard_List = ((CompanyJobCard[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CompanyJobCard[] CompanyJobCard_List) {
            this.UpdateMultipleAsync(CompanyJobCard_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CompanyJobCard[] CompanyJobCard_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        CompanyJobCard_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_KeyJobResponsibilities", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_KeyJobResponsibilities_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_KeyJobResponsibilities_Result")]
        public bool Delete_KeyJobResponsibilities(string KeyJobResponsibilities_Key) {
            object[] results = this.Invoke("Delete_KeyJobResponsibilities", new object[] {
                        KeyJobResponsibilities_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_KeyJobResponsibilitiesAsync(string KeyJobResponsibilities_Key) {
            this.Delete_KeyJobResponsibilitiesAsync(KeyJobResponsibilities_Key, null);
        }
        
        /// <remarks/>
        public void Delete_KeyJobResponsibilitiesAsync(string KeyJobResponsibilities_Key, object userState) {
            if ((this.Delete_KeyJobResponsibilitiesOperationCompleted == null)) {
                this.Delete_KeyJobResponsibilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_KeyJobResponsibilitiesOperationCompleted);
            }
            this.InvokeAsync("Delete_KeyJobResponsibilities", new object[] {
                        KeyJobResponsibilities_Key}, this.Delete_KeyJobResponsibilitiesOperationCompleted, userState);
        }
        
        private void OnDelete_KeyJobResponsibilitiesOperationCompleted(object arg) {
            if ((this.Delete_KeyJobResponsibilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_KeyJobResponsibilitiesCompleted(this, new Delete_KeyJobResponsibilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_Academics", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_Academics_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Academics_Result")]
        public bool Delete_Academics(string Academics_Key) {
            object[] results = this.Invoke("Delete_Academics", new object[] {
                        Academics_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_AcademicsAsync(string Academics_Key) {
            this.Delete_AcademicsAsync(Academics_Key, null);
        }
        
        /// <remarks/>
        public void Delete_AcademicsAsync(string Academics_Key, object userState) {
            if ((this.Delete_AcademicsOperationCompleted == null)) {
                this.Delete_AcademicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_AcademicsOperationCompleted);
            }
            this.InvokeAsync("Delete_Academics", new object[] {
                        Academics_Key}, this.Delete_AcademicsOperationCompleted, userState);
        }
        
        private void OnDelete_AcademicsOperationCompleted(object arg) {
            if ((this.Delete_AcademicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_AcademicsCompleted(this, new Delete_AcademicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_Experience", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_Experience_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Experience_Result")]
        public bool Delete_Experience(string Experience_Key) {
            object[] results = this.Invoke("Delete_Experience", new object[] {
                        Experience_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_ExperienceAsync(string Experience_Key) {
            this.Delete_ExperienceAsync(Experience_Key, null);
        }
        
        /// <remarks/>
        public void Delete_ExperienceAsync(string Experience_Key, object userState) {
            if ((this.Delete_ExperienceOperationCompleted == null)) {
                this.Delete_ExperienceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_ExperienceOperationCompleted);
            }
            this.InvokeAsync("Delete_Experience", new object[] {
                        Experience_Key}, this.Delete_ExperienceOperationCompleted, userState);
        }
        
        private void OnDelete_ExperienceOperationCompleted(object arg) {
            if ((this.Delete_ExperienceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_ExperienceCompleted(this, new Delete_ExperienceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_KnowledgeRequired", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_KnowledgeRequired_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_KnowledgeRequired_Result")]
        public bool Delete_KnowledgeRequired(string KnowledgeRequired_Key) {
            object[] results = this.Invoke("Delete_KnowledgeRequired", new object[] {
                        KnowledgeRequired_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_KnowledgeRequiredAsync(string KnowledgeRequired_Key) {
            this.Delete_KnowledgeRequiredAsync(KnowledgeRequired_Key, null);
        }
        
        /// <remarks/>
        public void Delete_KnowledgeRequiredAsync(string KnowledgeRequired_Key, object userState) {
            if ((this.Delete_KnowledgeRequiredOperationCompleted == null)) {
                this.Delete_KnowledgeRequiredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_KnowledgeRequiredOperationCompleted);
            }
            this.InvokeAsync("Delete_KnowledgeRequired", new object[] {
                        KnowledgeRequired_Key}, this.Delete_KnowledgeRequiredOperationCompleted, userState);
        }
        
        private void OnDelete_KnowledgeRequiredOperationCompleted(object arg) {
            if ((this.Delete_KnowledgeRequiredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_KnowledgeRequiredCompleted(this, new Delete_KnowledgeRequiredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_ProfessionalCourse", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_ProfessionalCourse_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_ProfessionalCourse_Result")]
        public bool Delete_ProfessionalCourse(string ProfessionalCourse_Key) {
            object[] results = this.Invoke("Delete_ProfessionalCourse", new object[] {
                        ProfessionalCourse_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_ProfessionalCourseAsync(string ProfessionalCourse_Key) {
            this.Delete_ProfessionalCourseAsync(ProfessionalCourse_Key, null);
        }
        
        /// <remarks/>
        public void Delete_ProfessionalCourseAsync(string ProfessionalCourse_Key, object userState) {
            if ((this.Delete_ProfessionalCourseOperationCompleted == null)) {
                this.Delete_ProfessionalCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_ProfessionalCourseOperationCompleted);
            }
            this.InvokeAsync("Delete_ProfessionalCourse", new object[] {
                        ProfessionalCourse_Key}, this.Delete_ProfessionalCourseOperationCompleted, userState);
        }
        
        private void OnDelete_ProfessionalCourseOperationCompleted(object arg) {
            if ((this.Delete_ProfessionalCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_ProfessionalCourseCompleted(this, new Delete_ProfessionalCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_ProfessionalMembership", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_ProfessionalMembership_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_ProfessionalMembership_Result")]
        public bool Delete_ProfessionalMembership(string ProfessionalMembership_Key) {
            object[] results = this.Invoke("Delete_ProfessionalMembership", new object[] {
                        ProfessionalMembership_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_ProfessionalMembershipAsync(string ProfessionalMembership_Key) {
            this.Delete_ProfessionalMembershipAsync(ProfessionalMembership_Key, null);
        }
        
        /// <remarks/>
        public void Delete_ProfessionalMembershipAsync(string ProfessionalMembership_Key, object userState) {
            if ((this.Delete_ProfessionalMembershipOperationCompleted == null)) {
                this.Delete_ProfessionalMembershipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_ProfessionalMembershipOperationCompleted);
            }
            this.InvokeAsync("Delete_ProfessionalMembership", new object[] {
                        ProfessionalMembership_Key}, this.Delete_ProfessionalMembershipOperationCompleted, userState);
        }
        
        private void OnDelete_ProfessionalMembershipOperationCompleted(object arg) {
            if ((this.Delete_ProfessionalMembershipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_ProfessionalMembershipCompleted(this, new Delete_ProfessionalMembershipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_Position_Supervising", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_Position_Supervising_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Position_Supervising_Result")]
        public bool Delete_Position_Supervising(string Position_Supervising_Key) {
            object[] results = this.Invoke("Delete_Position_Supervising", new object[] {
                        Position_Supervising_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_Position_SupervisingAsync(string Position_Supervising_Key) {
            this.Delete_Position_SupervisingAsync(Position_Supervising_Key, null);
        }
        
        /// <remarks/>
        public void Delete_Position_SupervisingAsync(string Position_Supervising_Key, object userState) {
            if ((this.Delete_Position_SupervisingOperationCompleted == null)) {
                this.Delete_Position_SupervisingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_Position_SupervisingOperationCompleted);
            }
            this.InvokeAsync("Delete_Position_Supervising", new object[] {
                        Position_Supervising_Key}, this.Delete_Position_SupervisingOperationCompleted, userState);
        }
        
        private void OnDelete_Position_SupervisingOperationCompleted(object arg) {
            if ((this.Delete_Position_SupervisingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_Position_SupervisingCompleted(this, new Delete_Position_SupervisingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/companyjobcard:Delete_Attachments", RequestNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", ResponseElementName="Delete_Attachments_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/companyjobcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Attachments_Result")]
        public bool Delete_Attachments(string Attachments_Key) {
            object[] results = this.Invoke("Delete_Attachments", new object[] {
                        Attachments_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_AttachmentsAsync(string Attachments_Key) {
            this.Delete_AttachmentsAsync(Attachments_Key, null);
        }
        
        /// <remarks/>
        public void Delete_AttachmentsAsync(string Attachments_Key, object userState) {
            if ((this.Delete_AttachmentsOperationCompleted == null)) {
                this.Delete_AttachmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_AttachmentsOperationCompleted);
            }
            this.InvokeAsync("Delete_Attachments", new object[] {
                        Attachments_Key}, this.Delete_AttachmentsOperationCompleted, userState);
        }
        
        private void OnDelete_AttachmentsOperationCompleted(object arg) {
            if ((this.Delete_AttachmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_AttachmentsCompleted(this, new Delete_AttachmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class CompanyJobCard {
        
        private string keyField;
        
        private string job_IDField;
        
        private string job_DesignationField;
        
        private string dimension_2Field;
        
        private string department_NameField;
        
        private string position_Reporting_toField;
        
        private string gradeField;
        
        private int no_of_PostsField;
        
        private bool no_of_PostsFieldSpecified;
        
        private int occupied_PositionField;
        
        private bool occupied_PositionFieldSpecified;
        
        private int vacancyField;
        
        private bool vacancyFieldSpecified;
        
        private string objectiveField;
        
        private Key_Job_Responsibilities[] keyJobResponsibilitiesField;
        
        private Company_Job_Education[] academicsField;
        
        private Company_Job_Experience[] experienceField;
        
        private Knowledge_Required[] knowledgeRequiredField;
        
        private Company_Job_Prof_course[] professionalCourseField;
        
        private Company_Job_Prof_Membership[] professionalMembershipField;
        
        private Positions_Supervising[] position_SupervisingField;
        
        private Job_Attachments[] attachmentsField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Job_ID {
            get {
                return this.job_IDField;
            }
            set {
                this.job_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Job_Designation {
            get {
                return this.job_DesignationField;
            }
            set {
                this.job_DesignationField = value;
            }
        }
        
        /// <remarks/>
        public string Dimension_2 {
            get {
                return this.dimension_2Field;
            }
            set {
                this.dimension_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Department_Name {
            get {
                return this.department_NameField;
            }
            set {
                this.department_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Position_Reporting_to {
            get {
                return this.position_Reporting_toField;
            }
            set {
                this.position_Reporting_toField = value;
            }
        }
        
        /// <remarks/>
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        public int No_of_Posts {
            get {
                return this.no_of_PostsField;
            }
            set {
                this.no_of_PostsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_of_PostsSpecified {
            get {
                return this.no_of_PostsFieldSpecified;
            }
            set {
                this.no_of_PostsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Occupied_Position {
            get {
                return this.occupied_PositionField;
            }
            set {
                this.occupied_PositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Occupied_PositionSpecified {
            get {
                return this.occupied_PositionFieldSpecified;
            }
            set {
                this.occupied_PositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Vacancy {
            get {
                return this.vacancyField;
            }
            set {
                this.vacancyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VacancySpecified {
            get {
                return this.vacancyFieldSpecified;
            }
            set {
                this.vacancyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Key_Job_Responsibilities[] KeyJobResponsibilities {
            get {
                return this.keyJobResponsibilitiesField;
            }
            set {
                this.keyJobResponsibilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Company_Job_Education[] Academics {
            get {
                return this.academicsField;
            }
            set {
                this.academicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Company_Job_Experience[] Experience {
            get {
                return this.experienceField;
            }
            set {
                this.experienceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Knowledge_Required[] KnowledgeRequired {
            get {
                return this.knowledgeRequiredField;
            }
            set {
                this.knowledgeRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Company_Job_Prof_course[] ProfessionalCourse {
            get {
                return this.professionalCourseField;
            }
            set {
                this.professionalCourseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Company_Job_Prof_Membership[] ProfessionalMembership {
            get {
                return this.professionalMembershipField;
            }
            set {
                this.professionalMembershipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Positions_Supervising[] Position_Supervising {
            get {
                return this.position_SupervisingField;
            }
            set {
                this.position_SupervisingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Job_Attachments[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Key_Job_Responsibilities {
        
        private string keyField;
        
        private string responsibility_CodeField;
        
        private Line_Type line_TypeField;
        
        private bool line_TypeFieldSpecified;
        
        private string remarksField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Responsibility_Code {
            get {
                return this.responsibility_CodeField;
            }
            set {
                this.responsibility_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Line_Type Line_Type {
            get {
                return this.line_TypeField;
            }
            set {
                this.line_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_TypeSpecified {
            get {
                return this.line_TypeFieldSpecified;
            }
            set {
                this.line_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public enum Line_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Header,
        
        /// <remarks/>
        Objective,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class CompanyJobCard_Filter {
        
        private CompanyJobCard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public CompanyJobCard_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public enum CompanyJobCard_Fields {
        
        /// <remarks/>
        Job_ID,
        
        /// <remarks/>
        Job_Designation,
        
        /// <remarks/>
        Dimension_2,
        
        /// <remarks/>
        Department_Name,
        
        /// <remarks/>
        Position_Reporting_to,
        
        /// <remarks/>
        Grade,
        
        /// <remarks/>
        No_of_Posts,
        
        /// <remarks/>
        Occupied_Position,
        
        /// <remarks/>
        Vacancy,
        
        /// <remarks/>
        Objective,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Job_Attachments {
        
        private string keyField;
        
        private string attachmentField;
        
        private string descriptionField;
        
        private string job_IDField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Job_ID {
            get {
                return this.job_IDField;
            }
            set {
                this.job_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Positions_Supervising {
        
        private string keyField;
        
        private string position_SupervisedField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Position_Supervised {
            get {
                return this.position_SupervisedField;
            }
            set {
                this.position_SupervisedField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Company_Job_Prof_Membership {
        
        private string keyField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Company_Job_Prof_course {
        
        private string keyField;
        
        private string qualification_CodeField;
        
        private string qualification_NameField;
        
        private int section_LevelField;
        
        private bool section_LevelFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Qualification_Code {
            get {
                return this.qualification_CodeField;
            }
            set {
                this.qualification_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Qualification_Name {
            get {
                return this.qualification_NameField;
            }
            set {
                this.qualification_NameField = value;
            }
        }
        
        /// <remarks/>
        public int Section_Level {
            get {
                return this.section_LevelField;
            }
            set {
                this.section_LevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Section_LevelSpecified {
            get {
                return this.section_LevelFieldSpecified;
            }
            set {
                this.section_LevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Knowledge_Required {
        
        private string keyField;
        
        private string knowledge_CodeField;
        
        private Line_Type_5 line_TypeField;
        
        private bool line_TypeFieldSpecified;
        
        private string remarksField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Knowledge_Code {
            get {
                return this.knowledge_CodeField;
            }
            set {
                this.knowledge_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Line_Type_5 Line_Type {
            get {
                return this.line_TypeField;
            }
            set {
                this.line_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_TypeSpecified {
            get {
                return this.line_TypeFieldSpecified;
            }
            set {
                this.line_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public enum Line_Type_5 {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Header,
        
        /// <remarks/>
        Objective,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Company_Job_Experience {
        
        private string keyField;
        
        private string industryField;
        
        private string industry_NameField;
        
        private Hierarchy_Level hierarchy_LevelField;
        
        private bool hierarchy_LevelFieldSpecified;
        
        private decimal no_of_YearsField;
        
        private bool no_of_YearsFieldSpecified;
        
        private decimal scoreField;
        
        private bool scoreFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Industry {
            get {
                return this.industryField;
            }
            set {
                this.industryField = value;
            }
        }
        
        /// <remarks/>
        public string Industry_Name {
            get {
                return this.industry_NameField;
            }
            set {
                this.industry_NameField = value;
            }
        }
        
        /// <remarks/>
        public Hierarchy_Level Hierarchy_Level {
            get {
                return this.hierarchy_LevelField;
            }
            set {
                this.hierarchy_LevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Hierarchy_LevelSpecified {
            get {
                return this.hierarchy_LevelFieldSpecified;
            }
            set {
                this.hierarchy_LevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal No_of_Years {
            get {
                return this.no_of_YearsField;
            }
            set {
                this.no_of_YearsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_of_YearsSpecified {
            get {
                return this.no_of_YearsFieldSpecified;
            }
            set {
                this.no_of_YearsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public enum Hierarchy_Level {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Consultant,
        
        /// <remarks/>
        Executive_Director,
        
        /// <remarks/>
        First_Level_Manager,
        
        /// <remarks/>
        Intern,
        
        /// <remarks/>
        Middle_Level_Manager,
        
        /// <remarks/>
        Supervisor,
        
        /// <remarks/>
        Support_Staff,
        
        /// <remarks/>
        Top_Level_Manager,
        
        /// <remarks/>
        Trainee_Attachee,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public partial class Company_Job_Education {
        
        private string keyField;
        
        private string field_of_EducationField;
        
        private string field_NameField;
        
        private Education_Level education_LevelField;
        
        private bool education_LevelFieldSpecified;
        
        private string qualification_CodeField;
        
        private string qualification_NameField;
        
        private Proficiency_Level proficiency_LevelField;
        
        private bool proficiency_LevelFieldSpecified;
        
        private decimal scoreField;
        
        private bool scoreFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Field_of_Education {
            get {
                return this.field_of_EducationField;
            }
            set {
                this.field_of_EducationField = value;
            }
        }
        
        /// <remarks/>
        public string Field_Name {
            get {
                return this.field_NameField;
            }
            set {
                this.field_NameField = value;
            }
        }
        
        /// <remarks/>
        public Education_Level Education_Level {
            get {
                return this.education_LevelField;
            }
            set {
                this.education_LevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Education_LevelSpecified {
            get {
                return this.education_LevelFieldSpecified;
            }
            set {
                this.education_LevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Qualification_Code {
            get {
                return this.qualification_CodeField;
            }
            set {
                this.qualification_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Qualification_Name {
            get {
                return this.qualification_NameField;
            }
            set {
                this.qualification_NameField = value;
            }
        }
        
        /// <remarks/>
        public Proficiency_Level Proficiency_Level {
            get {
                return this.proficiency_LevelField;
            }
            set {
                this.proficiency_LevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Proficiency_LevelSpecified {
            get {
                return this.proficiency_LevelFieldSpecified;
            }
            set {
                this.proficiency_LevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public enum Education_Level {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Professional,
        
        /// <remarks/>
        Certificate,
        
        /// <remarks/>
        Diploma,
        
        /// <remarks/>
        Higher_Post_Graduate_Diploma,
        
        /// <remarks/>
        Bachelors_Degree,
        
        /// <remarks/>
        Masters_Degree,
        
        /// <remarks/>
        Doctorate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/companyjobcard")]
    public enum Proficiency_Level {
        
        /// <remarks/>
        Not_Rated,
        
        /// <remarks/>
        First_Class,
        
        /// <remarks/>
        Second_Class_Upper,
        
        /// <remarks/>
        Second_Class_Lower,
        
        /// <remarks/>
        Second_Class,
        
        /// <remarks/>
        Pass,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyJobCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyJobCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyJobCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyJobCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyJobCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyJobCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyJobCard CompanyJobCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyJobCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyJobCard[] CompanyJobCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyJobCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyJobCard CompanyJobCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyJobCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyJobCard[] CompanyJobCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyJobCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_KeyJobResponsibilitiesCompletedEventHandler(object sender, Delete_KeyJobResponsibilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_KeyJobResponsibilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_KeyJobResponsibilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_AcademicsCompletedEventHandler(object sender, Delete_AcademicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_AcademicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_AcademicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_ExperienceCompletedEventHandler(object sender, Delete_ExperienceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_ExperienceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_ExperienceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_KnowledgeRequiredCompletedEventHandler(object sender, Delete_KnowledgeRequiredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_KnowledgeRequiredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_KnowledgeRequiredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_ProfessionalCourseCompletedEventHandler(object sender, Delete_ProfessionalCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_ProfessionalCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_ProfessionalCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_ProfessionalMembershipCompletedEventHandler(object sender, Delete_ProfessionalMembershipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_ProfessionalMembershipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_ProfessionalMembershipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_Position_SupervisingCompletedEventHandler(object sender, Delete_Position_SupervisingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_Position_SupervisingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_Position_SupervisingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Delete_AttachmentsCompletedEventHandler(object sender, Delete_AttachmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_AttachmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_AttachmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591